# Generated by Django 4.0.4 on 2022-05-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposial',
            new_name='Proposal',
        ),
    ]
