# Generated by Django 4.0.4 on 2022-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_proposial_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='proposal'),
        ),
    ]
